[lib]
crate-type = ["cdylib"]

[package]
name = "wordle_solver"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
serde = "1.0.216"
serde_json = "1.0.133"
wasm-bindgen = "0.2.99"
wasm-pack = "0.13.1"
getrandom = { version = "0.2", features = ["js"] }
